In [1]:
import numpy as np

In [6]:
data = [d.strip() for d in open('input.txt').readlines()]

In [13]:
chars = [ [int(c) for c in d] for d in data]

In [14]:
nums = np.array(chars)

In [15]:
nums

array([[0, 0, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 0],
       [1, 1, 0, ..., 1, 1, 0]])

In [21]:
gamma = (nums.mean(axis=0)>0.5).astype(np.int32)
eps = (nums.mean(axis=0)<0.5).astype(np.int32)

In [22]:
gamma,eps

(array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1], dtype=int32),
 array([1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0], dtype=int32))

In [38]:
g = int(''.join(map(str,gamma)),2)
e = int(''.join(map(str,eps)),2)

In [39]:
print(g*e)

1540244


In [44]:
def most_common_bit(arr, idx):
    s = 0
    for a in arr:
        s+=a[idx]
    s /= arr.shape[0]
    return (s>=0.5)*1

In [68]:
[most_common_bit(nums,i) for i in range(nums.shape[1])]

[0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1]

In [75]:
oxygen = None
short_list = nums
for i in range(nums.shape[1]):
    common_bit = most_common_bit(short_list,i)
    mask = short_list[:,i] == common_bit
    short_list = short_list[mask]
    print(common_bit, len(short_list))
    if len(short_list) == 1:
        print(short_list)
        oxygen = short_list[0]
        break

0 521
1 261
0 139
0 70
1 36
0 21
0 11
0 6
1 4
0 3
0 2
1 1
[[0 1 0 0 1 0 0 0 1 0 0 1]]


In [76]:
CO2 =None
short_list = nums
for i in range(nums.shape[1]):
    common_bit = 1-most_common_bit(short_list,i)
    mask = short_list[:,i] == common_bit
    short_list = short_list[mask]
    print(common_bit, len(short_list))
    if len(short_list) == 1:
        print(short_list)
        CO2 = short_list[0]
        break

1 479
1 231
1 115
0 55
0 27
0 13
1 6
0 2
0 1
[[1 1 1 0 0 0 1 0 0 1 0 1]]


In [77]:
o = int(''.join(map(str,oxygen)),2)
c = int(''.join(map(str,CO2)),2)
print(o*c)

4203981


In [82]:
int('0b11',0)

3

In [84]:
! pip install seaborn

     |████████████████████████████████| 292 kB 10.8 MB/s            
