In [1]:
import numpy as np

In [28]:
def fwd_diff(arr):
    return arr[1:]-arr[:-1]

In [35]:
data = open('Q1.txt').readlines()
data = list(map(int, data))
data =np.array(data)

In [36]:
np.sum(fwd_diff(data) >0)

1548

In [37]:
data[:10], data[-10:]

(array([157, 148, 149, 146, 144, 145, 162, 163, 164, 166]),
 array([7974, 7976, 7989, 7993, 8006, 8007, 8010, 8016, 8020, 8026]))

In [44]:
window = []
for i in range(len(data)-2):
    # print(data[i:i+3])
    window.append(np.sum(data[i:i+3]))
window = np.array(window)
print(window[:10], window[:-10])
print(len(window))

[454 443 439 435 451 470 489 493 503 525] [  454   443   439 ... 23750 23776 23804]
1998


In [45]:
np.sum(fwd_diff(window) >0)

1589

In [46]:
fwd_diff(window[:10])

array([-11,  -4,  -4,  16,  19,  19,   4,  10,  22])

In [48]:
data[1990:5001]

array([7974, 7976, 7989, 7993, 8006, 8007, 8010, 8016, 8020, 8026])

In [49]:
a =data

In [52]:
f=lambda a:sum([a[i+1]-a[i]>0for i in range(len(a)-1)])
f=lambda a:np.sum((a[1:]-a[:-1])>0)
f(a)

1548