In [1]:
import numpy as np

In [2]:
sample_data = """7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7"""

In [98]:
sample_data = open('input.txt').read()

In [99]:
first_line = sample_data.split('\n')[0]
called_numbers = first_line.split(',')
called_numbers = list(map(int, called_numbers))
called_numbers = np.array(called_numbers)

In [100]:
called_numbers

array([17, 11, 37,  7, 89, 48, 99, 28, 56, 55, 57, 27, 83, 59, 53, 72,  6,
       87, 33, 82, 13, 23, 35, 40, 71, 47, 78,  2, 39,  4, 51,  1, 67, 31,
       79, 69, 15, 73, 80, 22, 92, 95, 91, 43, 26, 97, 36, 34, 12, 96, 86,
       52, 66, 94, 61, 76, 64, 77, 85, 98, 42, 68, 84, 63, 60, 30, 65, 19,
       54, 58, 24, 20, 25, 75, 93, 16, 18, 44, 14, 88, 45, 10,  9,  3, 70,
       74, 81, 90, 46, 38, 21, 49, 29, 50,  0,  5,  8, 32, 62, 41])

In [101]:
boards = sample_data.split('\n\n')[1:]
boards = [ b.split() for b in boards ]
boards = [ list(map(int,b)) for b in boards ]
boards = [ np.reshape(b, (5,5)) for b in boards]

In [102]:
boards[:5]

[array([[57, 80, 91, 40, 12],
        [62, 36, 72,  0, 20],
        [55, 60, 25, 92, 96],
        [14,  2, 17, 18, 86],
        [ 1,  4, 90, 66, 38]]),
 array([[ 1, 25, 81, 16, 24],
        [33, 40, 86, 28, 96],
        [ 4, 97, 90, 32, 13],
        [50, 38, 35, 14, 56],
        [73, 42,  9, 36, 67]]),
 array([[46, 25, 28, 59, 88],
        [33, 48, 15,  0, 95],
        [16, 30, 24,  2, 71],
        [11, 81, 58, 70, 65],
        [37,  1, 26, 94, 75]]),
 array([[53, 56,  5, 72, 99],
        [46, 27, 23, 49,  4],
        [ 3, 93, 21, 65, 37],
        [35,  7, 50, 32, 24],
        [81, 78, 52, 54, 88]]),
 array([[76, 14, 58, 84, 17],
        [ 5, 89, 97, 57, 15],
        [19, 77, 35, 56, 93],
        [31, 71, 92,  2, 39],
        [10, 27, 91, 67, 47]])]

In [103]:
len(boards)

100

In [68]:
scorecard = np.isin(boards[2], called_numbers[:12])
rows = np.all(scorecard, axis=1)
cols = np.all(scorecard, axis=0)
print(scorecard)
print("rows", rows)
print("cols", cols)
is_a_winner = np.any(rows) or np.any(cols)
print("Winner ? ", is_a_winner)

[[ True  True  True  True  True]
 [False False False  True False]
 [False False  True False False]
 [False  True False False  True]
 [ True  True False False  True]]
rows [ True False False False False]
cols [False False False False False]
Winner ?  True


In [71]:
score = np.sum(boards[2][~scorecard]) * called_numbers[11]
print("score", score)

score 4512


In [104]:
def winning_score(board, called_numbers):
    """
    Returns
    i, score : int, int
        The amount of numbers required to win and the winning score
    """
    for i, num in enumerate(called_numbers):
        scorecard = np.isin(board, called_numbers[:i+1])
        rows = np.all(scorecard, axis=1)
        cols = np.all(scorecard, axis=0)
        is_a_winner = np.any(rows) or np.any(cols)
        if is_a_winner:
            score =  np.sum(board[~scorecard]) * num
            return (i, score)

In [105]:
winning_score(boards[2], called_numbers)

(70, 9624)

In [113]:
fastest_win = np.inf
fastest_score = None
fastest_board = None
fastest_index = None
for i, b in enumerate(boards):
    speed, score = winning_score(b, called_numbers)
    if speed < fastest_win:
        fastest_win = speed
        fastest_score = score
        fastest_board = b
        fastest_index = i
print("best score is", fastest_score)
print("fastest win:", fastest_win)
print("on board:", fastest_board)
print('index is', fastest_index)

best score is 55770
fastest win: 26
on board: [[16 62  3 75 84]
 [54 10  1  2 44]
 [21 42  0 99 64]
 [91 45 67 34 82]
 [83 78 17 53  6]]
index is 75


In [114]:
slowest_win = 0
slowest_score = None
slowest_board = None
slowest_index = None
for i, b in enumerate(boards):
    speed, score = winning_score(b, called_numbers)
    if speed > slowest_win:
        slowest_win = speed
        slowest_score = score
        slowest_board = b
        slowest_index = i
print("best score is", slowest_score)
print("slowest win:", slowest_win)
print("on board:", slowest_board)
print('index is', slowest_index)

best score is 2980
slowest win: 81
on board: [[61 52  9 18 70]
 [41 53 90 94 87]
 [80 20  0 11 42]
 [ 8 46 63 29  5]
 [34 15  7 91 10]]
index is 44
