In [2]:
import numpy as np

In [3]:
test = """0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2"""

In [29]:
def make_start_end(inputs):
    """
    Break input into a list of start locations and end locations
    
    return
    ------
    starts, ends : list, list
      list of [int,int] being the locations on the chart for the
      start/end of the lines
    """
    lines = inputs.split('\n')
    coords = [ l.split('->') for l in lines]
    starts = [ list(map(int,a[0].split(','))) for a in coords]
    ends = [ list(map(int,a[1].split(','))) for a in coords]
    return starts, ends

In [30]:
def make_chart(starts,ends):
    """
    Figure out the minimum size of the chart based on
    the start/end of the lines
    
    return
    ------
    chart : np.ndarray
      The chart of the sea floor.
    """
    mx_start = np.max(starts, axis=0)
    mx_end = np.max(ends, axis=0)
    size = np.max([mx_start, mx_end], axis=0) + np.array([1,1])
    chart = np.zeros(size, dtype=np.int)
    print(f"Chart is {size}")
    return chart

In [6]:
def is_udlr(start,end):
    """ Check if the start/end represents a horizontal or vertical line"""
    return (start[0] == end[0]) | (start[1] == end[1])

In [7]:
def fill_in(start, end, chart):
    """
    """
    # a,b -> c, d
    r = slice( min(start[0], end[0]), max(start[0], end[0])+1)
    c = slice( min(start[1], end[1]), max(start[1], end[1])+1)
    chart[r,c] +=1
    return

In [8]:
def solution1(inputs):
    starts, ends = make_start_end(inputs)
    chart = make_chart(starts, ends)
    for s, e in zip(starts, ends):
        #print(f"{s}->{e}")
        if is_udlr(s,e):
            #print('linear')
            fill_in(s,e,chart)
        else:
            #print('diag')
            pass
    print(chart)
    num_crossings = len(np.where(chart>=2)[0])
    return num_crossings

In [9]:
solution1(test)

Chart is [10 10]
[[0 0 0 0 0 0 0 0 0 2]
 [0 0 0 0 1 0 0 0 0 2]
 [0 1 1 0 1 0 0 0 0 2]
 [0 0 0 0 2 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0]
 [1 1 1 1 2 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]


/tmp/ipykernel_2249005/1658101582.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  chart = np.zeros(size, dtype=np.int)


5

In [10]:
inputs = open('input.txt').read()[:-1]
solution1(inputs)

Chart is [991 991]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


/tmp/ipykernel_2249005/1658101582.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  chart = np.zeros(size, dtype=np.int)


4873

In [27]:
def fill_in_diag(start, end, chart):
    """
    """
    # a,b -> c, d
    a,b = start
    c,d = end
    if a<=c:
        rows = list(range(a,c+1))
    else:
        rows = list(range(a,c-1,-1))
    if b<=d:
        cols = list(range(b,d+1))
    else:
        cols = list(range(b,d-1,-1))
#     print(start,end)
#     print(rows,cols)
    for i, (r,c) in enumerate(zip(rows,cols)):
        chart[r,c] +=1
    return

In [16]:
def solution2(inputs):
    starts, ends = make_start_end(inputs)
    chart = make_chart(starts, ends)
    for s, e in zip(starts, ends):
        #print(f"{s}->{e}")
        if is_udlr(s,e):
            #print('linear')
            fill_in(s,e,chart)
        else:
            #print('diag')
            fill_in_diag(s,e,chart)
    print(chart)
    num_crossings = len(np.where(chart>=2)[0])
    return num_crossings

In [14]:
inputs = open('input.txt').read()[:-1]

In [25]:
solution2(test)

Chart is [10 10]
[8, 0] [0, 8]
[8, 7, 6, 5, 4, 3, 2, 1, 0] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[6, 4] [2, 0]
[6, 5, 4, 3, 2] [4, 3, 2, 1, 0]
[0, 0] [8, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[5, 5] [8, 2]
[5, 6, 7, 8] [5, 4, 3, 2]
[[1 0 0 0 0 0 0 0 1 2]
 [0 1 0 0 1 0 0 1 0 2]
 [1 1 2 0 1 0 1 0 0 2]
 [0 1 0 1 2 1 0 0 0 1]
 [0 0 1 0 3 0 0 0 0 1]
 [0 0 0 2 1 2 0 0 0 1]
 [0 0 1 0 3 0 1 0 0 0]
 [1 2 1 2 2 0 0 1 0 0]
 [1 0 1 0 1 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0]]


/tmp/ipykernel_2249005/1658101582.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  chart = np.zeros(size, dtype=np.int)


12

In [28]:
solution2(inputs)

Chart is [991 991]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


/tmp/ipykernel_2249005/1658101582.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  chart = np.zeros(size, dtype=np.int)


19472